# Generated by Django 5.2.13 on 2026-05-14 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skill',
            field=models.CharField(choices=[('medical', 'Medical Support'), ('driving', 'Driving/Transport'), ('food', 'Food/Water Distribution'), ('logistics', 'Logistics/Coordination'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
